name: Android Test Workflow

on:
  workflow_call:

jobs:
  android-test:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Geetings
        uses: cchanka/github-actions-android-workflows/.github/actions/greetings@main
        with:
          who-to-greet: 'Nagarro'

      - name: Setup JAVA
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Running Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      
      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Android Unit Tests
          path: app/build/test-results/**/*.xml
          reporter: java-junit